# Generated by Django 5.1.2 on 2024-12-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatiProApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='about_me',
            field=models.TextField(null=True),
        ),
    ]
