# Generated by Django 5.1.2 on 2024-12-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatiProApp', '0002_professional_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='about_me',
            field=models.TextField(default='I am BatiPro Professional'),
        ),
    ]
