# Generated by Django 5.1.2 on 2024-12-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatiProApp', '0003_alter_professional_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
    ]
