# Generated by Django 5.1.2 on 2024-12-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatiProApp', '0004_professional_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
