# Generated by Django 5.1.2 on 2024-12-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatiProApp', '0005_professional_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='join_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
