# Generated by Django 5.1.2 on 2024-12-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatiProApp', '0006_professional_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
