# Generated by Django 5.1.2 on 2024-12-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BatiProApp', '0009_alter_marketowner_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketowner',
            name='status',
        ),
    ]
