# Generated by Django 5.1.2 on 2024-12-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatiProApp', '0010_remove_marketowner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketowner',
            name='join',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
