# Generated by Django 5.1.2 on 2024-12-04 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatiProApp', '0014_marketplace_map_alter_marketplace_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplace',
            name='note',
        ),
        migrations.CreateModel(
            name='AvisMarket',
            fields=[
                ('id_avis', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.DecimalField(decimal_places=1, max_digits=2)),
                ('commentaire', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BatiProApp.client')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='BatiProApp.marketplace')),
            ],
            options={
                'db_table': 'avis_market',
                'unique_together': {('marketplace', 'client')},
            },
        ),
    ]
