# Generated by Django 4.2.16 on 2025-01-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatiProApp', '0016_annoncemarket_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='cartier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
